version: '3'
services:
  clickhouse1:
    # image: clickhouse/clickhouse-server
    build: 
      dockerfile: Dockerfile
    ports:
      - "8002:9000"
      - "9123:8123"
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144

