version: '3'

services:
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - .docker-volume-minio:/data
    environment:
      MINIO_ROOT_USER: adminio
      MINIO_ROOT_PASSWORD: zzz
    command: server --console-address ":9001" /data

volumes:
  .docker-volume:
    driver: local
