version: '3'
services:
  zookeeper:
    container_name: zoo
    image: 'bitnami/zookeeper:latest'
    networks:
      - ch_replicated
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOOKEEPER_CLIENT_PORT=2181
    ports:
      - "2182:2181"
      - "2888:2888"
      - "3888:3888"
    
  clickhouse1:
    container_name: click1
    # image: clickhouse/clickhouse-server
    build: 
      dockerfile: Dockerfile
    ports:
      - "8002:9000"
      - "9123:8123"
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    networks:
      - ch_replicated
    depends_on:
      - zookeeper
      
  clickhouse2:
    container_name: click2
    # image: clickhouse/clickhouse-server
    build:  
      dockerfile: Dockerfile
    ports:
      - "8003:9000"
      - "9124:8123"
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    networks:
      - ch_replicated
    depends_on:
      - zookeeper
      
  clickhouse3:
    container_name: click3
    # image: clickhouse/clickhouse-server
    build: 
      dockerfile: Dockerfile
    ports:
      - "8004:9000"
      - "9125:8123"
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    networks:
      - ch_replicated
    depends_on:
      - zookeeper

  clickhouse4:
    container_name: click4
    # image: clickhouse/clickhouse-server
    build: 
      dockerfile: Dockerfile
    ports:
      - "8005:9000"
      - "9126:8123"
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    networks:
      - ch_replicated
    depends_on:
      - zookeeper

networks:
  ch_replicated:
    driver: bridge
